version: 2.1

executors:
  uptech_macos:
    macos:
      xcode: "11.1.0"
    shell: /bin/bash --login -eo pipefail
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8


commands:
  uptech_restore_cache:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "Cartfile.resolved" }}-{{ .Environment.CACHE_VERSION }}

  uptech_save_cache:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "Cartfile.resolved" }}-{{ .Environment.CACHE_VERSION }}
          paths: 
            - "Carthage/"

  install_dependencies:
    steps:
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Install Carthage & SwiftLint
          command: ./bin/upstall
      - run:
          name: Carthage Bootstrap
          command: carthage bootstrap --platform ios --cache-builds

  uptech_store_test_results:
    steps:
      - store_test_results:
          path: fastlane/test_output


jobs:
  build-and-test:
    executor: uptech_macos
    steps:
      - checkout
      - uptech_restore_cache
      - install_dependencies
      - uptech_save_cache
      - run:
          name: Build and run tests
          command: bundle exec fastlane test build_configuration:staging
      - uptech_store_test_results

  deploy_qa:
    executor: uptech_macos
    steps:
      - checkout
      - uptech_restore_cache
      - install_dependencies
      - uptech_save_cache
      - run:
          name: Build and run tests
          command: bundle exec fastlane test_then_deploy_qa
      - uptech_store_test_results

  deploy_staging:
    executor: uptech_macos
    steps:
      - checkout
      - uptech_restore_cache
      - install_dependencies
      - uptech_save_cache
      - run:
          name: Build and run tests
          command: bundle exec fastlane test_then_deploy_staging
      - uptech_store_test_results

  deploy_production:
    executor: uptech_macos
    steps:
      - checkout
      - uptech_restore_cache
      - install_dependencies
      - uptech_save_cache
      - run:
          name: Build and run tests
          command: bundle exec fastlane test_then_deploy_production
      - uptech_store_test_results

workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - develop
      - deploy_qa:
          filters:
            branches:
              only:
                - develop
